import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../styles/globals.css";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
  display: 'swap', // Isso ajuda no carregamento
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={`${poppins.className} ${poppins.variable} antialiased`}>
      <body className="bg-[#121212] text-neutral-100">
        {children}
      </body>
    </html>
  );
}